kind = "mobile"
previewPath = "/monterey-mobile/"
title = "Monterey Mobile"
version = "1.0.0"
id = "artifacts/sonoma-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/monterey-mobile/" ]
localPort = 25384

[services.development]
run = "pnpm --filter @workspace/sonoma-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sonoma-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/sonoma-mobile", "run", "serve" ]

[services.env]
PORT = "25384"
BASE_PATH = "/monterey-mobile/"
